### PR TITLE
Doc minor setting changes

### PR DESCRIPTION
**Pull request by Legersky**
- view button added (requires the newest furo, will work correctly once merged to main)
 - GitHub icon in the footer
 - showing tips delayed, top position

### CODE REVIEW

**Review by MatteoGallet — COMMENTED** [review]
I get a warning

" WARNING: unsupported theme option 'top_of_page_buttons' given"

**Comment by Legersky** [comment]
could you try `pip install --upgrade furo`?

**Comment by MatteoGallet** [comment]
> could you try `pip install --upgrade furo`?

Thanks, that solved it! Maybe we should mention that we should use the updated version of furo?

**Comment by Legersky** [comment]
Did you mean in the how-to?

**Review by MatteoGallet — APPROVED** [review]

**Pull request merged**
